bonxai_server_node:
  ros__parameters:
    use_sim_time: true
    frame_id: map
    topic_in: /shared/points

    occupancy:
      static_resolution: 0.10
      dynamic_resolution: 0.10
      occupancy_min_z: 0.25
      occupancy_max_z: 20.0
      occupancy_threshold: 0.50

    sensor_model:
      max_range: 100.0
      hit: 0.70
      miss: 0.10
      min: 0.08
      max: 0.85

    server:
      cleanup_interval_sec: 300.0

    map_storage:
      path: /home/raymond/SURF_2026/surf_ws/src/surf_multirobot_sim/maps/static_map.bonxai
      load_on_startup: true
      save_on_shutdown: true

    stats:
      enable_stats: true
      quick_stats: true
      publish_occupied_voxels: true
      static_publish_rate: 0.5
      dynamic_publish_rate: 10.0

    dynamic_obstacles:
      enabled: true
      decay_time_sec: 2.0
      decay_interval_sec: 0.25
      static_demotion_time_sec: 30.0
      static_stability_hits: 30
      static_stability_time_sec: 1.0
      min_probability: 0.05
